
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzlfeqyzuftvrujcjetq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bGZlcXl6dWZ0dnJ1amNqZXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjk3MTMsImV4cCI6MjA1OTg0NTcxM30.z3DZRtqqWIhkZfKsaXAwLHJinGtdO4Lbe8Zx90YYcxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
